AUDIO_ENABLE = no
TOUCH_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
CONSOLE_ENABLE = yes
ENCODER_ENABLE = yes

SRC += mtch6102.c i2c_master.c
