#ifdef RGBLIGHT_ENABLE

#define RGBLED_SPLIT {6, 6}

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE

#define RGBLIGHT_EFFECT_SNAKE_LENGTH RGBLED_NUM

#endif
